/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedBillsRouteImport } from './routes/_authed.bills'
import { Route as AuthedRecurringRouteImport } from './routes/_authed.recurring'
import { Route as AuthedRulesRouteImport } from './routes/_authed.rules'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed.transactions'
import { Route as InvitationsTokenRouteImport } from './routes/invitations.$token'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as AuthedAccountsIndexRouteImport } from './routes/_authed.accounts.index'
import { Route as AuthedAccountsAccountIdRouteImport } from './routes/_authed.accounts.$accountId'
import { Route as AuthedBudgetsIndexRouteImport } from './routes/_authed.budgets.index'
import { Route as AuthedBudgetsMonthRouteImport } from './routes/_authed.budgets.$month'
import { Route as AuthedGoalsIndexRouteImport } from './routes/_authed.goals.index'
import { Route as AuthedGoalsGoalIdRouteImport } from './routes/_authed.goals.$goalId'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed.settings.index'
import { Route as AuthedSettingsAssistantsRouteImport } from './routes/_authed.settings.assistants'
import { Route as AuthedSettingsBanksRouteImport } from './routes/_authed.settings.banks'
import { Route as AuthedSettingsCategoriesRouteImport } from './routes/_authed.settings.categories'
import { Route as AuthedSettingsDataRouteImport } from './routes/_authed.settings.data'
import { Route as AuthedSettingsInvestmentsRouteImport } from './routes/_authed.settings.investments'
import { Route as AuthedSettingsMembersRouteImport } from './routes/_authed.settings.members'
import { Route as AuthedSettingsMerchantsRouteImport } from './routes/_authed.settings.merchants'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed.settings.security'
import { Route as AuthedSettingsTagsRouteImport } from './routes/_authed.settings.tags'
import { Route as AuthedBudgetsMonthCategoriesRouteImport } from './routes/_authed.budgets.$month_.categories'
import { Route as AuthedBudgetsMonthEditRouteImport } from './routes/_authed.budgets.$month_.edit'
import { Route as AuthedSettingsBanksConnectionIdRouteImport } from './routes/_authed.settings.banks_.$connectionId'
import { Route as AuthedSettingsBanksCallbackRouteImport } from './routes/_authed.settings.banks_.callback'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillsRoute = AuthedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecurringRoute = AuthedRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRulesRoute = AuthedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountsIndexRoute = AuthedAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsAccountIdRoute = AuthedAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBudgetsIndexRoute = AuthedBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBudgetsMonthRoute = AuthedBudgetsMonthRouteImport.update({
  id: '/budgets/$month',
  path: '/budgets/$month',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsIndexRoute = AuthedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsGoalIdRoute = AuthedGoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAssistantsRoute =
  AuthedSettingsAssistantsRouteImport.update({
    id: '/assistants',
    path: '/assistants',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsBanksRoute = AuthedSettingsBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsCategoriesRoute =
  AuthedSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsDataRoute = AuthedSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsInvestmentsRoute =
  AuthedSettingsInvestmentsRouteImport.update({
    id: '/investments',
    path: '/investments',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsMembersRoute = AuthedSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsMerchantsRoute = AuthedSettingsMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsTagsRoute = AuthedSettingsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedBudgetsMonthCategoriesRoute =
  AuthedBudgetsMonthCategoriesRouteImport.update({
    id: '/budgets/$month_/categories',
    path: '/budgets/$month/categories',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBudgetsMonthEditRoute = AuthedBudgetsMonthEditRouteImport.update({
  id: '/budgets/$month_/edit',
  path: '/budgets/$month/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsBanksConnectionIdRoute =
  AuthedSettingsBanksConnectionIdRouteImport.update({
    id: '/banks_/$connectionId',
    path: '/banks/$connectionId',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsBanksCallbackRoute =
  AuthedSettingsBanksCallbackRouteImport.update({
    id: '/banks_/callback',
    path: '/banks/callback',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/bills': typeof AuthedBillsRoute
  '/recurring': typeof AuthedRecurringRoute
  '/rules': typeof AuthedRulesRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/transactions': typeof AuthedTransactionsRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/accounts/$accountId': typeof AuthedAccountsAccountIdRoute
  '/budgets/$month': typeof AuthedBudgetsMonthRoute
  '/goals/$goalId': typeof AuthedGoalsGoalIdRoute
  '/settings/assistants': typeof AuthedSettingsAssistantsRoute
  '/settings/banks': typeof AuthedSettingsBanksRoute
  '/settings/categories': typeof AuthedSettingsCategoriesRoute
  '/settings/data': typeof AuthedSettingsDataRoute
  '/settings/investments': typeof AuthedSettingsInvestmentsRoute
  '/settings/members': typeof AuthedSettingsMembersRoute
  '/settings/merchants': typeof AuthedSettingsMerchantsRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/settings/tags': typeof AuthedSettingsTagsRoute
  '/accounts/': typeof AuthedAccountsIndexRoute
  '/budgets/': typeof AuthedBudgetsIndexRoute
  '/goals/': typeof AuthedGoalsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/budgets/$month/categories': typeof AuthedBudgetsMonthCategoriesRoute
  '/budgets/$month/edit': typeof AuthedBudgetsMonthEditRoute
  '/settings/banks/$connectionId': typeof AuthedSettingsBanksConnectionIdRoute
  '/settings/banks/callback': typeof AuthedSettingsBanksCallbackRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/bills': typeof AuthedBillsRoute
  '/recurring': typeof AuthedRecurringRoute
  '/rules': typeof AuthedRulesRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/': typeof AuthedIndexRoute
  '/accounts/$accountId': typeof AuthedAccountsAccountIdRoute
  '/budgets/$month': typeof AuthedBudgetsMonthRoute
  '/goals/$goalId': typeof AuthedGoalsGoalIdRoute
  '/settings/assistants': typeof AuthedSettingsAssistantsRoute
  '/settings/banks': typeof AuthedSettingsBanksRoute
  '/settings/categories': typeof AuthedSettingsCategoriesRoute
  '/settings/data': typeof AuthedSettingsDataRoute
  '/settings/investments': typeof AuthedSettingsInvestmentsRoute
  '/settings/members': typeof AuthedSettingsMembersRoute
  '/settings/merchants': typeof AuthedSettingsMerchantsRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/settings/tags': typeof AuthedSettingsTagsRoute
  '/accounts': typeof AuthedAccountsIndexRoute
  '/budgets': typeof AuthedBudgetsIndexRoute
  '/goals': typeof AuthedGoalsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/budgets/$month/categories': typeof AuthedBudgetsMonthCategoriesRoute
  '/budgets/$month/edit': typeof AuthedBudgetsMonthEditRoute
  '/settings/banks/$connectionId': typeof AuthedSettingsBanksConnectionIdRoute
  '/settings/banks/callback': typeof AuthedSettingsBanksCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/_authed/bills': typeof AuthedBillsRoute
  '/_authed/recurring': typeof AuthedRecurringRoute
  '/_authed/rules': typeof AuthedRulesRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/accounts/$accountId': typeof AuthedAccountsAccountIdRoute
  '/_authed/budgets/$month': typeof AuthedBudgetsMonthRoute
  '/_authed/goals/$goalId': typeof AuthedGoalsGoalIdRoute
  '/_authed/settings/assistants': typeof AuthedSettingsAssistantsRoute
  '/_authed/settings/banks': typeof AuthedSettingsBanksRoute
  '/_authed/settings/categories': typeof AuthedSettingsCategoriesRoute
  '/_authed/settings/data': typeof AuthedSettingsDataRoute
  '/_authed/settings/investments': typeof AuthedSettingsInvestmentsRoute
  '/_authed/settings/members': typeof AuthedSettingsMembersRoute
  '/_authed/settings/merchants': typeof AuthedSettingsMerchantsRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRoute
  '/_authed/settings/tags': typeof AuthedSettingsTagsRoute
  '/_authed/accounts/': typeof AuthedAccountsIndexRoute
  '/_authed/budgets/': typeof AuthedBudgetsIndexRoute
  '/_authed/goals/': typeof AuthedGoalsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/budgets/$month_/categories': typeof AuthedBudgetsMonthCategoriesRoute
  '/_authed/budgets/$month_/edit': typeof AuthedBudgetsMonthEditRoute
  '/_authed/settings/banks_/$connectionId': typeof AuthedSettingsBanksConnectionIdRoute
  '/_authed/settings/banks_/callback': typeof AuthedSettingsBanksCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/bills'
    | '/recurring'
    | '/rules'
    | '/settings'
    | '/transactions'
    | '/invitations/$token'
    | '/oauth/consent'
    | '/accounts/$accountId'
    | '/budgets/$month'
    | '/goals/$goalId'
    | '/settings/assistants'
    | '/settings/banks'
    | '/settings/categories'
    | '/settings/data'
    | '/settings/investments'
    | '/settings/members'
    | '/settings/merchants'
    | '/settings/security'
    | '/settings/tags'
    | '/accounts/'
    | '/budgets/'
    | '/goals/'
    | '/settings/'
    | '/budgets/$month/categories'
    | '/budgets/$month/edit'
    | '/settings/banks/$connectionId'
    | '/settings/banks/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/sign-in'
    | '/bills'
    | '/recurring'
    | '/rules'
    | '/transactions'
    | '/invitations/$token'
    | '/oauth/consent'
    | '/'
    | '/accounts/$accountId'
    | '/budgets/$month'
    | '/goals/$goalId'
    | '/settings/assistants'
    | '/settings/banks'
    | '/settings/categories'
    | '/settings/data'
    | '/settings/investments'
    | '/settings/members'
    | '/settings/merchants'
    | '/settings/security'
    | '/settings/tags'
    | '/accounts'
    | '/budgets'
    | '/goals'
    | '/settings'
    | '/budgets/$month/categories'
    | '/budgets/$month/edit'
    | '/settings/banks/$connectionId'
    | '/settings/banks/callback'
  id:
    | '__root__'
    | '/_authed'
    | '/setup'
    | '/sign-in'
    | '/_authed/bills'
    | '/_authed/recurring'
    | '/_authed/rules'
    | '/_authed/settings'
    | '/_authed/transactions'
    | '/invitations/$token'
    | '/oauth/consent'
    | '/_authed/'
    | '/_authed/accounts/$accountId'
    | '/_authed/budgets/$month'
    | '/_authed/goals/$goalId'
    | '/_authed/settings/assistants'
    | '/_authed/settings/banks'
    | '/_authed/settings/categories'
    | '/_authed/settings/data'
    | '/_authed/settings/investments'
    | '/_authed/settings/members'
    | '/_authed/settings/merchants'
    | '/_authed/settings/security'
    | '/_authed/settings/tags'
    | '/_authed/accounts/'
    | '/_authed/budgets/'
    | '/_authed/goals/'
    | '/_authed/settings/'
    | '/_authed/budgets/$month_/categories'
    | '/_authed/budgets/$month_/edit'
    | '/_authed/settings/banks_/$connectionId'
    | '/_authed/settings/banks_/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bills': {
      id: '/_authed/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthedBillsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recurring': {
      id: '/_authed/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AuthedRecurringRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rules': {
      id: '/_authed/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthedRulesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/accounts/': {
      id: '/_authed/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthedAccountsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts/$accountId': {
      id: '/_authed/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthedAccountsAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/budgets/': {
      id: '/_authed/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof AuthedBudgetsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/budgets/$month': {
      id: '/_authed/budgets/$month'
      path: '/budgets/$month'
      fullPath: '/budgets/$month'
      preLoaderRoute: typeof AuthedBudgetsMonthRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/': {
      id: '/_authed/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthedGoalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/$goalId': {
      id: '/_authed/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthedGoalsGoalIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/assistants': {
      id: '/_authed/settings/assistants'
      path: '/assistants'
      fullPath: '/settings/assistants'
      preLoaderRoute: typeof AuthedSettingsAssistantsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/banks': {
      id: '/_authed/settings/banks'
      path: '/banks'
      fullPath: '/settings/banks'
      preLoaderRoute: typeof AuthedSettingsBanksRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/categories': {
      id: '/_authed/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthedSettingsCategoriesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/data': {
      id: '/_authed/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AuthedSettingsDataRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/investments': {
      id: '/_authed/settings/investments'
      path: '/investments'
      fullPath: '/settings/investments'
      preLoaderRoute: typeof AuthedSettingsInvestmentsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/members': {
      id: '/_authed/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthedSettingsMembersRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/merchants': {
      id: '/_authed/settings/merchants'
      path: '/merchants'
      fullPath: '/settings/merchants'
      preLoaderRoute: typeof AuthedSettingsMerchantsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/tags': {
      id: '/_authed/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof AuthedSettingsTagsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/budgets/$month_/categories': {
      id: '/_authed/budgets/$month_/categories'
      path: '/budgets/$month/categories'
      fullPath: '/budgets/$month/categories'
      preLoaderRoute: typeof AuthedBudgetsMonthCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/budgets/$month_/edit': {
      id: '/_authed/budgets/$month_/edit'
      path: '/budgets/$month/edit'
      fullPath: '/budgets/$month/edit'
      preLoaderRoute: typeof AuthedBudgetsMonthEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/banks_/$connectionId': {
      id: '/_authed/settings/banks_/$connectionId'
      path: '/banks/$connectionId'
      fullPath: '/settings/banks/$connectionId'
      preLoaderRoute: typeof AuthedSettingsBanksConnectionIdRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/banks_/callback': {
      id: '/_authed/settings/banks_/callback'
      path: '/banks/callback'
      fullPath: '/settings/banks/callback'
      preLoaderRoute: typeof AuthedSettingsBanksCallbackRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsAssistantsRoute: typeof AuthedSettingsAssistantsRoute
  AuthedSettingsBanksRoute: typeof AuthedSettingsBanksRoute
  AuthedSettingsCategoriesRoute: typeof AuthedSettingsCategoriesRoute
  AuthedSettingsDataRoute: typeof AuthedSettingsDataRoute
  AuthedSettingsInvestmentsRoute: typeof AuthedSettingsInvestmentsRoute
  AuthedSettingsMembersRoute: typeof AuthedSettingsMembersRoute
  AuthedSettingsMerchantsRoute: typeof AuthedSettingsMerchantsRoute
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRoute
  AuthedSettingsTagsRoute: typeof AuthedSettingsTagsRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsBanksConnectionIdRoute: typeof AuthedSettingsBanksConnectionIdRoute
  AuthedSettingsBanksCallbackRoute: typeof AuthedSettingsBanksCallbackRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAssistantsRoute: AuthedSettingsAssistantsRoute,
  AuthedSettingsBanksRoute: AuthedSettingsBanksRoute,
  AuthedSettingsCategoriesRoute: AuthedSettingsCategoriesRoute,
  AuthedSettingsDataRoute: AuthedSettingsDataRoute,
  AuthedSettingsInvestmentsRoute: AuthedSettingsInvestmentsRoute,
  AuthedSettingsMembersRoute: AuthedSettingsMembersRoute,
  AuthedSettingsMerchantsRoute: AuthedSettingsMerchantsRoute,
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRoute,
  AuthedSettingsTagsRoute: AuthedSettingsTagsRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsBanksConnectionIdRoute: AuthedSettingsBanksConnectionIdRoute,
  AuthedSettingsBanksCallbackRoute: AuthedSettingsBanksCallbackRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedBillsRoute: typeof AuthedBillsRoute
  AuthedRecurringRoute: typeof AuthedRecurringRoute
  AuthedRulesRoute: typeof AuthedRulesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAccountsAccountIdRoute: typeof AuthedAccountsAccountIdRoute
  AuthedBudgetsMonthRoute: typeof AuthedBudgetsMonthRoute
  AuthedGoalsGoalIdRoute: typeof AuthedGoalsGoalIdRoute
  AuthedAccountsIndexRoute: typeof AuthedAccountsIndexRoute
  AuthedBudgetsIndexRoute: typeof AuthedBudgetsIndexRoute
  AuthedGoalsIndexRoute: typeof AuthedGoalsIndexRoute
  AuthedBudgetsMonthCategoriesRoute: typeof AuthedBudgetsMonthCategoriesRoute
  AuthedBudgetsMonthEditRoute: typeof AuthedBudgetsMonthEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBillsRoute: AuthedBillsRoute,
  AuthedRecurringRoute: AuthedRecurringRoute,
  AuthedRulesRoute: AuthedRulesRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAccountsAccountIdRoute: AuthedAccountsAccountIdRoute,
  AuthedBudgetsMonthRoute: AuthedBudgetsMonthRoute,
  AuthedGoalsGoalIdRoute: AuthedGoalsGoalIdRoute,
  AuthedAccountsIndexRoute: AuthedAccountsIndexRoute,
  AuthedBudgetsIndexRoute: AuthedBudgetsIndexRoute,
  AuthedGoalsIndexRoute: AuthedGoalsIndexRoute,
  AuthedBudgetsMonthCategoriesRoute: AuthedBudgetsMonthCategoriesRoute,
  AuthedBudgetsMonthEditRoute: AuthedBudgetsMonthEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
