/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedOperationsRouteImport } from './routes/_authed.operations'
import { Route as AuthedComptesIndexRouteImport } from './routes/_authed.comptes.index'
import { Route as AuthedComptesAccountIdRouteImport } from './routes/_authed.comptes.$accountId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsRoute = AuthedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComptesIndexRoute = AuthedComptesIndexRouteImport.update({
  id: '/comptes/',
  path: '/comptes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComptesAccountIdRoute = AuthedComptesAccountIdRouteImport.update({
  id: '/comptes/$accountId',
  path: '/comptes/$accountId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/connexion': typeof ConnexionRoute
  '/setup': typeof SetupRoute
  '/operations': typeof AuthedOperationsRoute
  '/comptes/$accountId': typeof AuthedComptesAccountIdRoute
  '/comptes/': typeof AuthedComptesIndexRoute
}
export interface FileRoutesByTo {
  '/connexion': typeof ConnexionRoute
  '/setup': typeof SetupRoute
  '/operations': typeof AuthedOperationsRoute
  '/': typeof AuthedIndexRoute
  '/comptes/$accountId': typeof AuthedComptesAccountIdRoute
  '/comptes': typeof AuthedComptesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/setup': typeof SetupRoute
  '/_authed/operations': typeof AuthedOperationsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/comptes/$accountId': typeof AuthedComptesAccountIdRoute
  '/_authed/comptes/': typeof AuthedComptesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/setup'
    | '/operations'
    | '/comptes/$accountId'
    | '/comptes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connexion'
    | '/setup'
    | '/operations'
    | '/'
    | '/comptes/$accountId'
    | '/comptes'
  id:
    | '__root__'
    | '/_authed'
    | '/connexion'
    | '/setup'
    | '/_authed/operations'
    | '/_authed/'
    | '/_authed/comptes/$accountId'
    | '/_authed/comptes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operations': {
      id: '/_authed/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthedOperationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/comptes/': {
      id: '/_authed/comptes/'
      path: '/comptes'
      fullPath: '/comptes/'
      preLoaderRoute: typeof AuthedComptesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/comptes/$accountId': {
      id: '/_authed/comptes/$accountId'
      path: '/comptes/$accountId'
      fullPath: '/comptes/$accountId'
      preLoaderRoute: typeof AuthedComptesAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedOperationsRoute: typeof AuthedOperationsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedComptesAccountIdRoute: typeof AuthedComptesAccountIdRoute
  AuthedComptesIndexRoute: typeof AuthedComptesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOperationsRoute: AuthedOperationsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedComptesAccountIdRoute: AuthedComptesAccountIdRoute,
  AuthedComptesIndexRoute: AuthedComptesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
