/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedOperationsRouteImport } from './routes/_authed.operations'
import { Route as AuthedRecurrencesRouteImport } from './routes/_authed.recurrences'
import { Route as AuthedReglagesRouteImport } from './routes/_authed.reglages'
import { Route as AuthedReglesRouteImport } from './routes/_authed.regles'
import { Route as AuthedComptesIndexRouteImport } from './routes/_authed.comptes.index'
import { Route as AuthedComptesAccountIdRouteImport } from './routes/_authed.comptes.$accountId'
import { Route as AuthedReglagesIndexRouteImport } from './routes/_authed.reglages.index'
import { Route as AuthedReglagesCategoriesRouteImport } from './routes/_authed.reglages.categories'
import { Route as AuthedReglagesEtiquettesRouteImport } from './routes/_authed.reglages.etiquettes'
import { Route as AuthedReglagesMarchandsRouteImport } from './routes/_authed.reglages.marchands'
import { Route as AuthedReglagesSecuriteRouteImport } from './routes/_authed.reglages.securite'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsRoute = AuthedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecurrencesRoute = AuthedRecurrencesRouteImport.update({
  id: '/recurrences',
  path: '/recurrences',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReglagesRoute = AuthedReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReglesRoute = AuthedReglesRouteImport.update({
  id: '/regles',
  path: '/regles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComptesIndexRoute = AuthedComptesIndexRouteImport.update({
  id: '/comptes/',
  path: '/comptes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComptesAccountIdRoute = AuthedComptesAccountIdRouteImport.update({
  id: '/comptes/$accountId',
  path: '/comptes/$accountId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReglagesIndexRoute = AuthedReglagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedReglagesRoute,
} as any)
const AuthedReglagesCategoriesRoute =
  AuthedReglagesCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthedReglagesRoute,
  } as any)
const AuthedReglagesEtiquettesRoute =
  AuthedReglagesEtiquettesRouteImport.update({
    id: '/etiquettes',
    path: '/etiquettes',
    getParentRoute: () => AuthedReglagesRoute,
  } as any)
const AuthedReglagesMarchandsRoute = AuthedReglagesMarchandsRouteImport.update({
  id: '/marchands',
  path: '/marchands',
  getParentRoute: () => AuthedReglagesRoute,
} as any)
const AuthedReglagesSecuriteRoute = AuthedReglagesSecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => AuthedReglagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/connexion': typeof ConnexionRoute
  '/setup': typeof SetupRoute
  '/operations': typeof AuthedOperationsRoute
  '/recurrences': typeof AuthedRecurrencesRoute
  '/reglages': typeof AuthedReglagesRouteWithChildren
  '/regles': typeof AuthedReglesRoute
  '/comptes/$accountId': typeof AuthedComptesAccountIdRoute
  '/reglages/categories': typeof AuthedReglagesCategoriesRoute
  '/reglages/etiquettes': typeof AuthedReglagesEtiquettesRoute
  '/reglages/marchands': typeof AuthedReglagesMarchandsRoute
  '/reglages/securite': typeof AuthedReglagesSecuriteRoute
  '/comptes/': typeof AuthedComptesIndexRoute
  '/reglages/': typeof AuthedReglagesIndexRoute
}
export interface FileRoutesByTo {
  '/connexion': typeof ConnexionRoute
  '/setup': typeof SetupRoute
  '/operations': typeof AuthedOperationsRoute
  '/recurrences': typeof AuthedRecurrencesRoute
  '/regles': typeof AuthedReglesRoute
  '/': typeof AuthedIndexRoute
  '/comptes/$accountId': typeof AuthedComptesAccountIdRoute
  '/reglages/categories': typeof AuthedReglagesCategoriesRoute
  '/reglages/etiquettes': typeof AuthedReglagesEtiquettesRoute
  '/reglages/marchands': typeof AuthedReglagesMarchandsRoute
  '/reglages/securite': typeof AuthedReglagesSecuriteRoute
  '/comptes': typeof AuthedComptesIndexRoute
  '/reglages': typeof AuthedReglagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/setup': typeof SetupRoute
  '/_authed/operations': typeof AuthedOperationsRoute
  '/_authed/recurrences': typeof AuthedRecurrencesRoute
  '/_authed/reglages': typeof AuthedReglagesRouteWithChildren
  '/_authed/regles': typeof AuthedReglesRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/comptes/$accountId': typeof AuthedComptesAccountIdRoute
  '/_authed/reglages/categories': typeof AuthedReglagesCategoriesRoute
  '/_authed/reglages/etiquettes': typeof AuthedReglagesEtiquettesRoute
  '/_authed/reglages/marchands': typeof AuthedReglagesMarchandsRoute
  '/_authed/reglages/securite': typeof AuthedReglagesSecuriteRoute
  '/_authed/comptes/': typeof AuthedComptesIndexRoute
  '/_authed/reglages/': typeof AuthedReglagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/setup'
    | '/operations'
    | '/recurrences'
    | '/reglages'
    | '/regles'
    | '/comptes/$accountId'
    | '/reglages/categories'
    | '/reglages/etiquettes'
    | '/reglages/marchands'
    | '/reglages/securite'
    | '/comptes/'
    | '/reglages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connexion'
    | '/setup'
    | '/operations'
    | '/recurrences'
    | '/regles'
    | '/'
    | '/comptes/$accountId'
    | '/reglages/categories'
    | '/reglages/etiquettes'
    | '/reglages/marchands'
    | '/reglages/securite'
    | '/comptes'
    | '/reglages'
  id:
    | '__root__'
    | '/_authed'
    | '/connexion'
    | '/setup'
    | '/_authed/operations'
    | '/_authed/recurrences'
    | '/_authed/reglages'
    | '/_authed/regles'
    | '/_authed/'
    | '/_authed/comptes/$accountId'
    | '/_authed/reglages/categories'
    | '/_authed/reglages/etiquettes'
    | '/_authed/reglages/marchands'
    | '/_authed/reglages/securite'
    | '/_authed/comptes/'
    | '/_authed/reglages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operations': {
      id: '/_authed/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthedOperationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recurrences': {
      id: '/_authed/recurrences'
      path: '/recurrences'
      fullPath: '/recurrences'
      preLoaderRoute: typeof AuthedRecurrencesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reglages': {
      id: '/_authed/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof AuthedReglagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/regles': {
      id: '/_authed/regles'
      path: '/regles'
      fullPath: '/regles'
      preLoaderRoute: typeof AuthedReglesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/comptes/': {
      id: '/_authed/comptes/'
      path: '/comptes'
      fullPath: '/comptes/'
      preLoaderRoute: typeof AuthedComptesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/comptes/$accountId': {
      id: '/_authed/comptes/$accountId'
      path: '/comptes/$accountId'
      fullPath: '/comptes/$accountId'
      preLoaderRoute: typeof AuthedComptesAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reglages/': {
      id: '/_authed/reglages/'
      path: '/'
      fullPath: '/reglages/'
      preLoaderRoute: typeof AuthedReglagesIndexRouteImport
      parentRoute: typeof AuthedReglagesRoute
    }
    '/_authed/reglages/categories': {
      id: '/_authed/reglages/categories'
      path: '/categories'
      fullPath: '/reglages/categories'
      preLoaderRoute: typeof AuthedReglagesCategoriesRouteImport
      parentRoute: typeof AuthedReglagesRoute
    }
    '/_authed/reglages/etiquettes': {
      id: '/_authed/reglages/etiquettes'
      path: '/etiquettes'
      fullPath: '/reglages/etiquettes'
      preLoaderRoute: typeof AuthedReglagesEtiquettesRouteImport
      parentRoute: typeof AuthedReglagesRoute
    }
    '/_authed/reglages/marchands': {
      id: '/_authed/reglages/marchands'
      path: '/marchands'
      fullPath: '/reglages/marchands'
      preLoaderRoute: typeof AuthedReglagesMarchandsRouteImport
      parentRoute: typeof AuthedReglagesRoute
    }
    '/_authed/reglages/securite': {
      id: '/_authed/reglages/securite'
      path: '/securite'
      fullPath: '/reglages/securite'
      preLoaderRoute: typeof AuthedReglagesSecuriteRouteImport
      parentRoute: typeof AuthedReglagesRoute
    }
  }
}

interface AuthedReglagesRouteChildren {
  AuthedReglagesCategoriesRoute: typeof AuthedReglagesCategoriesRoute
  AuthedReglagesEtiquettesRoute: typeof AuthedReglagesEtiquettesRoute
  AuthedReglagesMarchandsRoute: typeof AuthedReglagesMarchandsRoute
  AuthedReglagesSecuriteRoute: typeof AuthedReglagesSecuriteRoute
  AuthedReglagesIndexRoute: typeof AuthedReglagesIndexRoute
}

const AuthedReglagesRouteChildren: AuthedReglagesRouteChildren = {
  AuthedReglagesCategoriesRoute: AuthedReglagesCategoriesRoute,
  AuthedReglagesEtiquettesRoute: AuthedReglagesEtiquettesRoute,
  AuthedReglagesMarchandsRoute: AuthedReglagesMarchandsRoute,
  AuthedReglagesSecuriteRoute: AuthedReglagesSecuriteRoute,
  AuthedReglagesIndexRoute: AuthedReglagesIndexRoute,
}

const AuthedReglagesRouteWithChildren = AuthedReglagesRoute._addFileChildren(
  AuthedReglagesRouteChildren,
)

interface AuthedRouteChildren {
  AuthedOperationsRoute: typeof AuthedOperationsRoute
  AuthedRecurrencesRoute: typeof AuthedRecurrencesRoute
  AuthedReglagesRoute: typeof AuthedReglagesRouteWithChildren
  AuthedReglesRoute: typeof AuthedReglesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedComptesAccountIdRoute: typeof AuthedComptesAccountIdRoute
  AuthedComptesIndexRoute: typeof AuthedComptesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOperationsRoute: AuthedOperationsRoute,
  AuthedRecurrencesRoute: AuthedRecurrencesRoute,
  AuthedReglagesRoute: AuthedReglagesRouteWithChildren,
  AuthedReglesRoute: AuthedReglesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedComptesAccountIdRoute: AuthedComptesAccountIdRoute,
  AuthedComptesIndexRoute: AuthedComptesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
