import type { LucideIcon } from "lucide-react";

import {
	BabyIcon,
	BanknoteIcon,
	BikeIcon,
	BookOpenIcon,
	BriefcaseIcon,
	BusIcon,
	CarIcon,
	CircleDollarSignIcon,
	CoffeeIcon,
	CoinsIcon,
	CreditCardIcon,
	DogIcon,
	DramaIcon,
	DumbbellIcon,
	FuelIcon,
	GiftIcon,
	GraduationCapIcon,
	HandHelpingIcon,
	HeartIcon,
	HouseIcon,
	LandmarkIcon,
	LightbulbIcon,
	MusicIcon,
	PiggyBankIcon,
	PillIcon,
	PlaneIcon,
	ReceiptIcon,
	ShieldIcon,
	ShirtIcon,
	ShoppingBagIcon,
	ShoppingCartIcon,
	SmartphoneIcon,
	TagIcon,
	TrainFrontIcon,
	TvIcon,
	UtensilsIcon,
	WifiIcon,
	WrenchIcon,
} from "lucide-react";

import type { CategoryIcon } from "@archant/data/category-presets";

/**
 * The component for each icon name the API accepts. `satisfies` makes a name
 * added to `CATEGORY_ICONS` without its component fail `typecheck`, rather
 * than render nothing.
 */
export const CATEGORY_ICON_COMPONENTS = {
	"circle-dollar-sign": CircleDollarSignIcon,
	"shopping-bag": ShoppingBagIcon,
	utensils: UtensilsIcon,
	bus: BusIcon,
	house: HouseIcon,
	lightbulb: LightbulbIcon,
	wifi: WifiIcon,
	shield: ShieldIcon,
	pill: PillIcon,
	landmark: LandmarkIcon,
	receipt: ReceiptIcon,
	drama: DramaIcon,
	plane: PlaneIcon,
	"hand-helping": HandHelpingIcon,
	"piggy-bank": PiggyBankIcon,
	tag: TagIcon,
	"shopping-cart": ShoppingCartIcon,
	car: CarIcon,
	fuel: FuelIcon,
	"train-front": TrainFrontIcon,
	bike: BikeIcon,
	baby: BabyIcon,
	dog: DogIcon,
	"graduation-cap": GraduationCapIcon,
	dumbbell: DumbbellIcon,
	shirt: ShirtIcon,
	gift: GiftIcon,
	heart: HeartIcon,
	briefcase: BriefcaseIcon,
	wrench: WrenchIcon,
	smartphone: SmartphoneIcon,
	tv: TvIcon,
	music: MusicIcon,
	"book-open": BookOpenIcon,
	coffee: CoffeeIcon,
	banknote: BanknoteIcon,
	coins: CoinsIcon,
	"credit-card": CreditCardIcon,
} satisfies Record<CategoryIcon, LucideIcon>;
